// Adding a key to a file that already holds funded keys.
//
// The one property that makes this safe to run against a funded install: the
// existing bytes come back out unchanged. Everything else is convenience.

import { execFileSync } from "node:child_process";
import { chmodSync, mkdtempSync, readFileSync, rmSync, statSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, describe, expect, it } from "vitest";
import { ALL_WALLET_IDS, BANK_WALLET_ID, WALLET_IDS, keyVarFor } from "@/config/wallets";

const root = process.cwd();
let dir: string;

afterEach(() => {
  if (dir) rmSync(dir, { recursive: true, force: true });
});

/** A file shaped like a real one: seven funded keys and the surrounding text. */
function sevenKeyFile(): string {
  return [
    "# Generated by npm run generate-wallets. Private keys: never commit this file.",
    "# It is gitignored, and a test fails if that ever stops being true.",
    "",
    "WALLET_BACKEND=viem",
    "# Optional. Defaults to the public Base Sepolia endpoint, which is rate limited.",
    "# RPC_URL=https://sepolia.base.org",
    "",
    ...WALLET_IDS.map((id, i) => `${keyVarFor(id)}=0x${String(i + 1).repeat(64).slice(0, 64)}`),
    "",
  ].join("\n");
}

function run(envFile: string, args: string[] = ["--add"]): string {
  return execFileSync("npx", ["tsx", "scripts/generate-wallets.ts", ...args], {
    cwd: root,
    encoding: "utf8",
    env: { ...process.env, SERVPIT_ENV_FILE: envFile },
  });
}

const write = (body: string): string => {
  dir = mkdtempSync(join(tmpdir(), "servpit-addkey-"));
  const file = join(dir, ".env.local");
  writeFileSync(file, body, { mode: 0o600 });
  return file;
};

describe("generate-wallets --add", () => {
  it("adds one line per missing wallet and leaves the seven existing keys byte identical", () => {
    const before = sevenKeyFile();
    const file = write(before);
    const output = run(file);
    const after = readFileSync(file, "utf8");

    // The whole original file is the prefix of the new one. Nothing was
    // rewritten, reordered or reformatted.
    expect(after.startsWith(before)).toBe(true);

    // One line per wallet the file was missing, and nothing else. No banner,
    // no dated comment, so a diff against a backup is one line per new
    // wallet and trivially reviewable.
    const missing = ALL_WALLET_IDS.filter((id) => !before.includes(`${keyVarFor(id)}=`));
    const added = after.slice(before.length).split("\n").filter((l) => l.length > 0);
    expect(added).toHaveLength(missing.length);
    expect(added.some((l) => new RegExp(`^${keyVarFor(BANK_WALLET_ID)}=0x[0-9a-f]{64}$`).test(l))).toBe(true);
    for (const line of added) expect(line).toMatch(/^SERVPIT_KEY_[A-Z]+=0x[0-9a-f]{64}$/);
    expect(after.split("\n").length).toBe(before.split("\n").length + missing.length);

    // Every original key line survives exactly as it was, at the same index.
    const afterLines = after.split("\n");
    for (const [i, line] of before.split("\n").entries()) {
      if (!line.startsWith("SERVPIT_KEY_")) continue;
      expect(afterLines[i]).toBe(line);
    }
    expect(after.split("\n").filter((l) => l.startsWith("SERVPIT_KEY_"))).toHaveLength(ALL_WALLET_IDS.length);

    expect(output).toContain(BANK_WALLET_ID);
    expect(output).not.toMatch(/0x[0-9a-f]{64}/);
  });

  it("prints the new address and never the new key", () => {
    const file = write(sevenKeyFile());
    const output = run(file);
    const key = readFileSync(file, "utf8").match(new RegExp(`${keyVarFor(BANK_WALLET_ID)}=(0x[0-9a-f]{64})`))![1];
    expect(output).not.toContain(key);
    expect(output).toMatch(/0x[0-9a-fA-F]{40}\b/);
  });

  it("does nothing on a second run, so it is safe to repeat", () => {
    const file = write(sevenKeyFile());
    run(file);
    const afterFirst = readFileSync(file, "utf8");
    const output = run(file);
    expect(readFileSync(file, "utf8")).toBe(afterFirst);
    expect(output).toMatch(/Nothing to add/);
  });

  it("keeps the file readable only by its owner", () => {
    const file = write(sevenKeyFile());
    chmodSync(file, 0o600);
    run(file);
    expect(statSync(file).mode & 0o777).toBe(0o600);
  });

  it("adds every missing key, not only the bank", () => {
    const partial = sevenKeyFile().split("\n").filter((l) => !l.startsWith(keyVarFor(WALLET_IDS[1]))).join("\n");
    const file = write(partial);
    run(file);
    const after = readFileSync(file, "utf8");
    for (const id of ALL_WALLET_IDS) expect(after).toContain(`${keyVarFor(id)}=0x`);
    expect(after.startsWith(partial)).toBe(true);
  });

  it("refuses to add to a file that does not exist", () => {
    dir = mkdtempSync(join(tmpdir(), "servpit-addkey-"));
    expect(() => run(join(dir, ".env.local"))).toThrow();
  });

  it("still refuses a bare run against an existing file, and points at --add", () => {
    const file = write(sevenKeyFile());
    const before = readFileSync(file, "utf8");
    let stderr = "";
    try {
      run(file, []);
    } catch (e) {
      stderr = String((e as { stderr?: Buffer }).stderr ?? "");
    }
    expect(stderr).toContain("--add");
    expect(readFileSync(file, "utf8")).toBe(before);
  });
});
