// Generates one private key per wallet and writes a .env.local template.
//
//   npm run generate-wallets
//
// Keys are written to .env.local only, which is gitignored. Nothing is
// printed except addresses: a key that reaches a terminal is a key in a
// scrollback buffer, a screen recording and a shell history file.
//
// The file is written to a temporary staging path first and moved into place,
// so an interrupted run cannot leave a half written key file behind. The
// staging path is removed on every exit, successful or not.

import { spawnSync } from "node:child_process";
import { existsSync, mkdtempSync, renameSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { generatePrivateKey, privateKeyToAccount } from "viem/accounts";
import { FUNDER_WALLET_ID, WALLET_IDS, keyVarFor } from "../src/config/wallets";

const repoRoot = resolve(import.meta.dirname, "..");
// SERVPIT_ENV_FILE exists so tests can run this in a sandbox. It cannot be
// used to smuggle keys into the repository: the guard below refuses any path
// git would track.
const envPath = resolve(process.env.SERVPIT_ENV_FILE ?? join(repoRoot, ".env.local"));

/**
 * Refuses to write key material anywhere git would pick it up. A path outside
 * the repository is fine; a path inside it must be gitignored.
 */
function assertUntracked(target: string): void {
  const inRepo = target === repoRoot || target.startsWith(repoRoot + "/");
  if (!inRepo) return;
  const ignored = spawnSync("git", ["check-ignore", "-q", target], { cwd: repoRoot }).status === 0;
  if (!ignored) {
    throw new Error(`refusing to write keys to ${target}: it is inside the repository and not gitignored`);
  }
}

function main(): void {
  if (existsSync(envPath) && !process.argv.includes("--force")) {
    console.error(`${envPath} already exists. Refusing to overwrite keys that may hold funds.`);
    console.error("Pass --force only if you are certain those wallets are empty.");
    process.exitCode = 1;
    return;
  }

  const wallets = WALLET_IDS.map((id) => {
    const privateKey = generatePrivateKey();
    return { id, privateKey, address: privateKeyToAccount(privateKey).address };
  });

  const lines = [
    "# Generated by npm run generate-wallets. Private keys: never commit this file.",
    "# It is gitignored, and a test fails if that ever stops being true.",
    "",
    "WALLET_BACKEND=viem",
    "# Optional. Defaults to the public Base Sepolia endpoint, which is rate limited.",
    "# RPC_URL=https://sepolia.base.org",
    "",
    ...wallets.map((w) => `${keyVarFor(w.id)}=${w.privateKey}`),
    "",
  ];

  // Staged then moved, so an interrupted run leaves no partial key file.
  assertUntracked(envPath);
  const staging = mkdtempSync(join(tmpdir(), "servpit-keys-"));
  const stagedFile = join(staging, "env.local");
  try {
    writeFileSync(stagedFile, lines.join("\n"), { mode: 0o600 });
    if (!existsSync(dirname(envPath))) throw new Error(`no such directory: ${dirname(envPath)}`);
    renameSync(stagedFile, envPath);
  } finally {
    rmSync(staging, { recursive: true, force: true });
  }

  console.log(`Wrote ${WALLET_IDS.length} keys to ${envPath} (mode 600, gitignored).\n`);
  console.log("Addresses, which are the only part safe to share:");
  for (const w of wallets) console.log(`  ${w.id.padEnd(6)} ${w.address}`);

  const funder = wallets.find((w) => w.id === FUNDER_WALLET_ID)!;
  console.log(`\nFund this address first, from a Base Sepolia faucet:\n\n  ${funder.address}\n`);
  console.log("Suggested amount: 0.02 ETH, which covers the fan out and many rounds of gas.");
  console.log("Faucets: https://portal.cdp.coinbase.com/products/faucet or https://www.alchemy.com/faucets/base-sepolia");
  console.log("\nThen fan it out to the other six:\n\n  npm run fund-wallets\n");
}

main();
